### ISSUE TITLE
What happened to the examples

### ISSUE THREAD

**Issue by AlessandroVol23** [cdkbook/examples#3]
Hi 👋🏽

Love your book so far! I just wanted to check your examples and I couldn't see any. Am I missing something or have you removed them?

Thanks!

**Comment by rportugal** [comment]
I'm looking for the `project-layout` examples, any updates @mbonig ? According to section 5.4.1 they should be available? Thanks.

**Comment by mbonig** [comment]
Take a look here: https://github.com/cdkbook/examples/tree/main/chapters/project-layout

Is there anything I missed in that folder?

**Comment by rob3c** [comment]
That linked folder only seems to contain placeholder readme files.

**Comment by mbonig** [comment]
You are correct. I wonder if I never got commits pushed. Will fix this up.... Sorry about that.

**Comment by mbonig** [comment]
Please open up new issues with specific examples you'd like to see and I'll get them created. Sorry for the lack of content.
