### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by lukiwlosek** [cdkbook/examples#4]
Hey, just reading through the book and wanted to see the examples, but I cannot find any looking at `chapters/lots-of-lamdas` specifically.

**Comment by mbonig** [comment]
@lukiwlosek you're right. In the last couple of years you're apparently the first one to notice. I'll take a look and see if I can get that added.

**Comment by lukiwlosek** [comment]
The book is great btw, thanks for looking into it ;)

**Comment by rob3c** [comment]
> @lukiwlosek you're right. In the last couple of years you're apparently the first one to notice. I'll take a look and see if I can get that added.

@mbonig Except for the [earlier issue](https://github.com/cdkbook/examples/issues/3) you closed without actually fixing them, of course 🙄

My guess is people assumed (like I did) that commenting here is a waste of time, and the authors promised more than they could deliver. Whatever insight might be had from the book itself is all you actually get, as-is.

**Comment by mbonig** [comment]
> > @lukiwlosek you're right. In the last couple of years you're apparently the first one to notice. I'll take a look and see if I can get that added.
> 
> @mbonig Except for the [earlier issue](https://github.com/cdkbook/examples/issues/3) you closed without actually fixing them, of course 🙄
> 
> My guess is people assumed (like I did) that commenting here is a waste of time, and the authors promised more than they could deliver. Whatever insight might be had from the book itself is all you actually get, as-is.

@rob3c I can sense your frustration, and I'm sorry I never delivered the examples that I promised from the book. Please keep an eye on the repository and I'll add them. I'll start with this one in this issue. As I mentioned in the other issue I closed, if you can tell me what specific examples you'd like me to prioritize, I'll do that.

**Comment by lukiwlosek** [comment]
@mbonig your example from the reinvent lectures proved to be nice and good, if you can point that repo here then it creates less confusion for people reading the book

**Comment by mbonig** [comment]
> @mbonig your example from the reinvent lectures proved to be nice and good, if you can point that repo here then it creates less confusion for people reading the book

https://github.com/mbonig/reinvent
