### ISSUE TITLE
Adding more examples

### ISSUE THREAD

**Issue by atulgoel126** [cdkbook/examples#5]
Hello @mbonig!

I am interested in adding a few examples. I am also trying to get better with CDK. If you have any specific examples in mind, I would like to add them.

If you don't, would you mind if I add a few of my own? Of course, any feedback would be great!

Thanks!

**Comment by mbonig** [comment]
This examples repository was originally intended for specific examples from the book. The work was lost when a laptop crashed so they never made it in and customer desire never seemed high enough to redo the work. 

thank you for the offer, but we won't be accepting outside examples at this time.
